name: sportsman
description: "Sportsman application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  result_transfer:
    git:
      url: https://github.com/orient-mark/result-transfer.git
      ref: dev
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  path_provider: ^2.1.3
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  mobile_scanner: ^7.4.2
  pretty_qr_code: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  mobx_codegen: ^2.6.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
